### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by diepmiho** [xyroot/esx_prioritycooldown#1]
not working error in server.lua.

**Comment by xyroot** [comment]
What error are you getting? @diepmiho

**Comment by diepmiho** [comment]
the symbol * in esx.playerLoaded and if i remove it server.lua in #7

**Comment by diepmiho** [comment]
im sorry i forgot to reply

**Comment by xyroot** [comment]
Oversight by me, should be fixed now. Sorry!
