### ISSUE TITLE
still not fix bro help i really need this kind of prioritycooldown :(

### ISSUE THREAD

**Issue by diepmiho** [xyroot/esx_prioritycooldown#2]
Error loading script server.lua in resource @esx_prioritycooldown/server.lua:7 attempt to call a nil value (field 'RegisterCommand') failed to load script.

**Comment by xyroot** [comment]
Are you using essentialmode? If so you need to convert the registercommands to the correct essentialmode format. 
This one needs es_extended 1.2 without essentialmode

**Comment by diepmiho** [comment]
Okay thank you sir ill try it :)
